# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

    org = Org.where(name: 'Identified').first_or_create()

    Beer.destroy_all
    OrgBeerSelection.destroy_all

    Beer.create([
                  { name: '21st Amendment IPA'                , brewed_by: '21st Amendment'                        , origin: 'San Francisco, CA, USA'  , style: 'IPA'                       , abv: 6.7, description: "Deep golden color. Citrus and piney hop aromas. Assertive malt backbone supporting the overwhelming bitterness. Dry hopped in the fermenter with four types of hops giving an explosive hop aroma." },
                  { name: 'Alaskan Amber'                     , brewed_by: 'Alaskan Brewing Co.'                   , origin: 'Juneau, AK, USA'         , style: 'Altbier'                   , abv: 5.0, description: "Richly malty and long on the palate, with just enough hop backing to make this beautiful amber colored 'alt' style beer notably well balanced." },
                  { name: 'Anchor California Lager'           , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Lager'                     , abv: 4.9, description: "Our California Lager is also a single-hop beer, using only fresh, whole Cluster hops, all descended from an old line originally grown in California. Cluster has a long history as a “dual-purpose hop” for both bittering and aroma, which creates a flavor profile like no other. Brewed with San Francisco tap water, fresh from Yosemite, and fermented with our own special strain of lager yeast, our California Lager is kräusened in the traditional manner and lagered in our cellars. The result is a uniquely sessionable lager beer, which is maltier, hoppier, and somewhat stronger than modern American lagers. Its brilliant golden color, lingering effervescence, balanced depth of flavor, distinctive aroma, and smooth finish make this inaugural brew of the Anchor Brewing Zymaster™ Series a delightful tribute to the rich heritage and traditions of California brewing." },
                  { name: 'Anchor Liberty Ale'                , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'American Pale Ale'         , abv: 5.9, description: "San Francisco's famous Liberty Ale was first brewed on the 18th of April, 1975 to celebrate the 200th anniversary of Paul Revere's historic ride. It is virtually handmade by the brewers of Anchor Steam Beer in one of the smallest and most traditional breweries in the world. Liberty Ale is made with the finest barley malt, fresh, whole hops, top fermenting yeast, pure water and the simple natural methods which reflect our exceptional respect for the ancient art of brewing. It is 'dry hopped', a classic ale tradition, and slowly completes its fermentation in sealed vats in out cellars. This unique process creates Liberty Ale's distinctive bouquet and uncommonly delicate, entirely natural carbonation." },
                  { name: 'Anchor Porter'                     , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Porter'                    , abv: 5.6, description: "Anchor Porter is a unique dark brew, which was introduced by Anchor in the early 1970s. Anchor Porter, like all of Anchor Brewing Company's products, is brewed with only natural ingredients. Specially roasted dark malts are used, along with a top-fermenting yeast. The brew is hopped at a very high rate, and is naturally carbonated to produce an intensely rich flavor and thick creamy head." },
                  { name: 'Anchor Steam'                      , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'California Common / Steam' , abv: 4.9, description: "San Francisco's famous Anchor Steam®, the classic of American brewing tradition since 1896, is virtually handmade, with an exceptional respect for the ancient art of brewing. The deep amber color, thick creamy head, and rich flavor all testify to our traditional brewing methods. Anchor Steam is unique, for our brewing process has evolved over many decades and is like no other in the world." },
                  { name: 'Anchor Zymaster Harvest One'       , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Pale Ale'                  , abv: 7.2, description: "Zymaster Series No. 5 (7.2% ABV) is made with a special blend of pale, caramel, and Munich malts, which contribute a distinctively complex maltiness and deep golden color. Nugget hops give it a tangy bitterness. But the hallmark of Zymaster 5: Harvest One American Pale Ale is the intriguingly novel aroma of an experimental new hop, which was used liberally in both the brewhouse and the cellar. A late addition to the boil plus dry hopping provides Harvest One with an incredibly lively hop aroma reminiscent of tree-ripened peaches, with just a hint of fresh melon. The result is a uniquely exciting new beer unlike anything brewed or tasted before." },
                  { name: 'Anderson Valley Boont Amber Ale'   , brewed_by: 'Anderson Valley Brewing Company'       , origin: 'Boonville, CA, USA'      , style: 'Amber Ale'                 , abv: 5.8, description: "Boont Amber Ale is a medium bodied pale ale with a beatiful copper color, a robust head, and the rich flavor of caramel malt. This very smooth and exceptionally drinkable beer is excellent with steaks, chicken, pasta, and other flavorful meals." },
                  { name: 'Blue Moon Belgian White'           , brewed_by: 'Blue Moon Brewing Company'             , origin: 'Golden, CO, USA'         , style: 'Witbier'                   , abv: 5.4, description: "An unfiltered wheat ale spiced in the Belgian tradition for an uncommonly smooth taste. Gold medalist (white beer) at 1995 World Beer Championships, silver medalist (white beer) at 1996 and 1997 World Beer Championships." },
                  { name: 'Chimay Premiere (Red)'             , brewed_by: 'Chimay'                                , origin: 'Baileux, Belgium'        , style: 'Abbey Dubbel'              , abv: 7.0, description: "Topped with a creamy head, it gives off a light, fruity apricot aroma produced by the fermentation. The taste perceived in the mouth is a balance confirming the fruity nuances noticed in the fragrance. Its taste, which imparts a silky sensation to the tongue, is made refreshing by a light touch of bitterness. To the palate, the taster perceives a pleasant astringency which complements the flavour qualities of this beer very harmoniously." },
                  { name: 'Dogfish Head 90 Minute IPA'        , brewed_by: 'Dogfish Head Brewery'                  , origin: 'Milton, DE, USA'         , style: 'Imperial IPA'              , abv: 9.0, description: "An Imperial I.P.A. brewed to be savored from a snifter. A big beer with a great malt backbone that stands up to the extreme hopping rate. Descriptors: Brandied fuitcake, raisiny, citrusy. This beer ages well!" },
                  { name: 'Dos Equis XX Special Lager'        , brewed_by: 'Femsa'                                 , origin: 'Monterrey/Veracruz-Llave, Mexico', style: 'Pale Lager'        , abv: 4.45, description: "Dos Equis Special Lager is a refreshing, crisp, golden, lager style beer imported from Mexico. Made with roasted malts, choice hops, a unique strain of yeast and purified water, this distinctive brew is known simply as “Lager” in its homeland." },
                  { name: 'Mendocino Eye of the Hawk'         , brewed_by: 'Mendocino Brewing Company'             , origin: 'Ukiah, CA, USA'          , style: 'Strong Ale'   , abv: 8.0, description: "Eye of the Hawk is an excellent, strong, rich bodied ale that is 'Bottle Conditioned' to perfection. 'Eye' is coppery reddish-amber in color and its unique taste is the result of a judicious mix of caramel and pale malted barley, balanced with Cluster, Cascade and Saaz hops. This gives the Eye its luxurious flavor, substantial mouth-feel and that slightly dry finish. Eye of the Hawk has garnered a cult following that is enviable." }
                  #{ name: 'Firestone Walker DBA'              , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                  #{ name: ''           , brewed_by: ''  , origin: '', style: ''   , abv: 0, description: "" },
                ]) do |b|
        OrgBeerSelection.create(org: org, beer: b)
    end




