# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

    org = Org.where(name: 'Identified', reminder_email: 'kegmaster@identified.com').first_or_create()

    Beer.destroy_all
    OrgBeerSelection.destroy_all

    Beer.create([
                  { name: '21st Amendment IPA'                , brewed_by: '21st Amendment'                        , origin: 'San Francisco, CA, USA'  , style: 'IPA'                       , abv: 6.7, description: "Deep golden color. Citrus and piney hop aromas. Assertive malt backbone supporting the overwhelming bitterness. Dry hopped in the fermenter with four types of hops giving an explosive hop aroma." },
                  { name: 'Alaskan Amber'                     , brewed_by: 'Alaskan Brewing Co.'                   , origin: 'Juneau, AK, USA'         , style: 'Altbier'                   , abv: 5.0, description: "Richly malty and long on the palate, with just enough hop backing to make this beautiful amber colored 'alt' style beer notably well balanced." },
                  { name: 'Anchor California Lager'           , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Lager'                     , abv: 4.9, description: "Our California Lager is also a single-hop beer, using only fresh, whole Cluster hops, all descended from an old line originally grown in California. Cluster has a long history as a “dual-purpose hop” for both bittering and aroma, which creates a flavor profile like no other. Brewed with San Francisco tap water, fresh from Yosemite, and fermented with our own special strain of lager yeast, our California Lager is kräusened in the traditional manner and lagered in our cellars. The result is a uniquely sessionable lager beer, which is maltier, hoppier, and somewhat stronger than modern American lagers. Its brilliant golden color, lingering effervescence, balanced depth of flavor, distinctive aroma, and smooth finish make this inaugural brew of the Anchor Brewing Zymaster™ Series a delightful tribute to the rich heritage and traditions of California brewing." },
                  { name: 'Anchor Liberty Ale'                , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'American Pale Ale'         , abv: 5.9, description: "San Francisco's famous Liberty Ale was first brewed on the 18th of April, 1975 to celebrate the 200th anniversary of Paul Revere's historic ride. It is virtually handmade by the brewers of Anchor Steam Beer in one of the smallest and most traditional breweries in the world. Liberty Ale is made with the finest barley malt, fresh, whole hops, top fermenting yeast, pure water and the simple natural methods which reflect our exceptional respect for the ancient art of brewing. It is 'dry hopped', a classic ale tradition, and slowly completes its fermentation in sealed vats in out cellars. This unique process creates Liberty Ale's distinctive bouquet and uncommonly delicate, entirely natural carbonation." },
                  { name: 'Anchor Porter'                     , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Porter'                    , abv: 5.6, description: "Anchor Porter is a unique dark brew, which was introduced by Anchor in the early 1970s. Anchor Porter, like all of Anchor Brewing Company's products, is brewed with only natural ingredients. Specially roasted dark malts are used, along with a top-fermenting yeast. The brew is hopped at a very high rate, and is naturally carbonated to produce an intensely rich flavor and thick creamy head." },
                  { name: 'Anchor Steam'                      , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'California Common / Steam' , abv: 4.9, description: "San Francisco's famous Anchor Steam®, the classic of American brewing tradition since 1896, is virtually handmade, with an exceptional respect for the ancient art of brewing. The deep amber color, thick creamy head, and rich flavor all testify to our traditional brewing methods. Anchor Steam is unique, for our brewing process has evolved over many decades and is like no other in the world." },
                  { name: 'Anchor Zymaster Harvest One'       , brewed_by: 'Anchor Brewing Company'                , origin: 'San Francisco, CA, USA'  , style: 'Pale Ale'                  , abv: 7.2, description: "Zymaster Series No. 5 (7.2% ABV) is made with a special blend of pale, caramel, and Munich malts, which contribute a distinctively complex maltiness and deep golden color. Nugget hops give it a tangy bitterness. But the hallmark of Zymaster 5: Harvest One American Pale Ale is the intriguingly novel aroma of an experimental new hop, which was used liberally in both the brewhouse and the cellar. A late addition to the boil plus dry hopping provides Harvest One with an incredibly lively hop aroma reminiscent of tree-ripened peaches, with just a hint of fresh melon. The result is a uniquely exciting new beer unlike anything brewed or tasted before." },
                  { name: 'Anderson Valley Boont Amber Ale'   , brewed_by: 'Anderson Valley Brewing Company'       , origin: 'Boonville, CA, USA'      , style: 'Amber Ale'                 , abv: 5.8, description: "Boont Amber Ale is a medium bodied pale ale with a beatiful copper color, a robust head, and the rich flavor of caramel malt. This very smooth and exceptionally drinkable beer is excellent with steaks, chicken, pasta, and other flavorful meals." },
                  { name: 'Blue Moon Belgian White'           , brewed_by: 'Blue Moon Brewing Company'             , origin: 'Golden, CO, USA'         , style: 'Witbier'                   , abv: 5.4, description: "An unfiltered wheat ale spiced in the Belgian tradition for an uncommonly smooth taste. Gold medalist (white beer) at 1995 World Beer Championships, silver medalist (white beer) at 1996 and 1997 World Beer Championships." },
                  { name: 'Chimay Premiere (Red)'             , brewed_by: 'Chimay'                                , origin: 'Baileux, Belgium'        , style: 'Abbey Dubbel'              , abv: 7.0, description: "Topped with a creamy head, it gives off a light, fruity apricot aroma produced by the fermentation. The taste perceived in the mouth is a balance confirming the fruity nuances noticed in the fragrance. Its taste, which imparts a silky sensation to the tongue, is made refreshing by a light touch of bitterness. To the palate, the taster perceives a pleasant astringency which complements the flavour qualities of this beer very harmoniously." },
                  { name: 'Dogfish Head 90 Minute IPA'        , brewed_by: 'Dogfish Head Brewery'                  , origin: 'Milton, DE, USA'         , style: 'Imperial IPA'              , abv: 9.0, description: "An Imperial I.P.A. brewed to be savored from a snifter. A big beer with a great malt backbone that stands up to the extreme hopping rate. Descriptors: Brandied fuitcake, raisiny, citrusy. This beer ages well!" },
                  { name: 'Dos Equis XX Special Lager'        , brewed_by: 'Femsa'                                 , origin: 'Monterrey/Veracruz-Llave, Mexico', style: 'Pale Lager'        , abv: 4.45, description: "Dos Equis Special Lager is a refreshing, crisp, golden, lager style beer imported from Mexico. Made with roasted malts, choice hops, a unique strain of yeast and purified water, this distinctive brew is known simply as “Lager” in its homeland." },
                  { name: 'Mendocino Eye of the Hawk'         , brewed_by: 'Mendocino Brewing Company'             , origin: 'Ukiah, CA, USA'          , style: 'Strong Ale'                , abv: 8.0, description: "Eye of the Hawk is an excellent, strong, rich bodied ale that is 'Bottle Conditioned' to perfection. 'Eye' is coppery reddish-amber in color and its unique taste is the result of a judicious mix of caramel and pale malted barley, balanced with Cluster, Cascade and Saaz hops. This gives the Eye its luxurious flavor, substantial mouth-feel and that slightly dry finish. Eye of the Hawk has garnered a cult following that is enviable." },
                  { name: 'Firestone Walker DBA'              , brewed_by: 'Firestone Walker Brewing Co'           , origin: 'Paso Robles, CA, USA'    , style: 'English Pale Ale'          , abv: 5.0, description: "A British Pale Ale never tasted so fresh. We challenge our good friends across the pond to match this one. Can’t be done. We’ve honored the traditions of the great British Pale brewers of Burton-on-Trent using our patented Firestone Union oak barrels. You’re left with a mild blend of vanilla and toasted oak flavor touched with an elegant hint of English noble hops. DBA is the flagship of our company and wildly popular." },
                  { name: 'Gordon Biersch Marzen'             , brewed_by: 'Gordon Biersch Brewery'                , origin: 'Las Vegas, NV, USA'      , style: 'Marzen / Oktoberfest'      , abv: 5.7, description: "Our most popular beer, Marzen is a smooth, mildly sweet, auburn colored lager. This beer originates from Bavaria where it was brewed in March and stored in caves to be enjoyed during warmer weather. At the end of September, any remaining kegs of Marzen were consumed during the two week celebration which became known as Oktoberfest." },
                  { name: 'Green Flash'                       , brewed_by: 'Green Flash Brewing Co.'               , origin: 'San Diego, CA, USA'      , style: 'IPA'                       , abv: 7.0, description: "San Diego IPA, as it has come to be known by many, is pale in color, super-hoppy, high-gravity, yet a highly quaffable ale. Our Imperial IPA is created in this new tradition with intense hop flavors and aromas from a unique blend of Summit and Nugget hops." },
                  { name: 'Hoegaarden Original White Ale'     , brewed_by: 'Brouwerij Hoegaarden (Interbrew)'      , origin: 'Hoegaarden, Belgium'     , style: 'Witbier'                   , abv: 4.9, description: "A delicious and surprising refreshing taste, naturally cloudy and brewed using a unique recipe of wheat, malted barley, and a subtle hint of coriander and orange peel." },
                  { name: 'Kona Longboard Lager'              , brewed_by: 'Kona Brewing Company'                  , origin: 'Kailua Kona, HI, USA'    , style: 'Lager'   , abv: 4.6, description: "Longboard Island Lager is a smooth refreshing lager fermented and aged for five weeks at cold temperatures to yield its exceptionally smooth flavor. A delicate, slightly spicy hop aroma complements the malty body of this beer." },
                  { name: 'New Belgium Fat Tire'              , brewed_by: 'New Belgium Brewing Company'           , origin: 'Fort Collins, CO, USA'   , style: 'Amber Ale'   , abv: 5.3, description: "Like the ageless delight of pedaling a bicycle, Fat Tire Amber Ale’s appeal is in its feat of balance: Toasty malt flavors (sorta like biscuits just pulled from the oven) coasting in equilibrium with crisp hoppiness. Delicious stability - in the world of sometimes-precarious beer flavors – is perhaps what prompted one consumer who wrote us to say, “this beer just makes you smile.” Fat Tire’s depth of flavor, achieved with neither a disproportionate sway toward hops or malts, tandems well with a full spectrum of today’s engaging cuisines. Salmon, dry-aged cheeses, roasted chilies, omelets at midnight, sweet potato French fries and just about anything with grill marks or garlic are just a few of the edibles we like to partner up with our Amber Ale. Fat Tire is so named for the bike trip Jeff took through Belgium that greatly inspired his homebrewing efforts." },
                  { name: 'North Coast PranQster'             , brewed_by: 'North Coast Brewing Company'           , origin: 'Fort Bragg, CA, USA'     , style: 'Belgian Ale'   , abv: 7.6, description: "Belgian Style Golden Ale. Belgian Ales represent the height of the brewers' art. Sophisticated brewing techniques, yeast blends and unique flavoring elements have elevated the beers of Belgium to the status enjoyed by wine in other countries. PranQster follows in this tradition using a mixed culture of antique yeast strains that produce a floral nose, a full fruity flavor and a clean finish" },
                  { name: 'Bear Republic Racer 5 IPA'         , brewed_by: 'Bear Republic Brewing Company'         , origin: 'Healdsburg, CA, USA'     , style: 'IPA'   , abv: 7.0, description: "This is a hoppy IPA. Did I say hops? Your brewer is a hop head! This is a full bodied beer using American grains. The goal was to create a base for showing off the unique floral qualities of two Pacific Northwest hops, Columbus and Cascade. Columbus is a new hybrid High Alpha Acid hop used mostly for bittering, but used heavily as an aromatic in this strong brew. Cascade is the balance that ties the malt and bittering hops together. It is a true specialty ale and is our brewer's statement on this style. 2004 L.A. Commercial Brewing Competition, Silver Medal Winner; 2004 World Beer Cup, Silver Medal Winner; 2001 Real Ale Festival, San Diego, Gold Medal Winner; 2001 Real Ale Festival, Chicago, Gold Medal Winner; 1999 Great Amercian Beer Festival, Gold Medal Winner - og 1.070, ABV 7.0%, IBU 69. California State Fair Bronze Medal, 1997 Beerfest Invitational. - og 1.070, ABV 7.0%, IBU 69." },
                  { name: 'North Coast Scrimshaw Pils'        , brewed_by: 'North Coast Brewing Company'           , origin: 'Fort Bragg, CA, USA'     , style: 'Bohemian / Czech Pilsener'   , abv: 4.4, description: "Named for the delicate engravings popularized by 19th century seafarers, Scrimshaw is a fresh tasting Pilsner brewed in the finest European tradition using Munich malt and, Hallertauer and Tettnang hops. Scrimshaw has a subtle hop character, a crisp, clean palate, and a dry finish." },
                  { name: 'Sierra Nevada Pale Ale'            , brewed_by: 'Sierra Nevada Brewing Company'         , origin: 'Chico, CA, USA', style: 'American Pale Ale'   , abv: 5.6, description: "Our most popular beer, Sierra Nevada Pale Ale, is a delightful interpretation of a classic style. It has a deep amber color and an exceptionally full-bodied, complex character. Generous quantities of premium Cascade hops give the Pale Ale its fragrant bouquet and spicy flavor." },
                  { name: 'Speakeasy Big Daddy IPA'           , brewed_by: 'Speakeasy Ales and Lagers'             , origin: 'San Francisco, CA, USA', style: 'IPA'   , abv: 6.5, description: "No lightweight, Big Daddy IPA tips the scales with a huge hop flavor and a clean, dry finish that leaves the scene without a trace." },
                  { name: 'Speakeasy Prohibition Ale'         , brewed_by: 'Speakeasy Ales and Lagers'             , origin: 'San Francisco, CA, USA', style: 'Amber Ale'   , abv: 6.1, description: "This amber ale has a deep red color and a light carbonation. It has a piney hop aroma along with sweet caramely malt. Full bodied and crisp, this beer has a toasty caramel flavor and fruity and peppery character as well. Definitely one of the more complex and enjoyable ambers out there." },
                  { name: 'Talon Double IPA'                  , brewed_by: 'Mendocino Brewing Company'             , origin: 'Ukiah, CA, USA', style: 'IPA'   , abv: 10.0, description: "An aggressive and old-school American Double IPA here, and a well named one, as this beer rips out your palate and the flies off to regurgitate it into the mouths of its frenzied young. Its combo of five malts and six hops creates a unique experience too. Anyone who touts themselves as a true hophead should seek out this beer now. Malts: Specialty 2 Row, Wheat, Munich, Vienna, CaraMunich 40. Hops: Warrior, Cascade, Amarillo, Summit, Pilgrim, Centennial. Dry Hop: Amarillo, Summit, Simcoe." },
                  { name: 'Widmer Brothers Hefeweizen'        , brewed_by: 'Widmer Brothers Brewing Company'       , origin: 'Portland, OR, USA', style: 'Hefeweizen'   , abv: 4.9, description: "A golden unfiltered wheat beer that is truly cloudy and clearly superb. Ever since Widmer introduced Hefeweizen to America in 1986, ours has been the standard by which all other Hefeweizens are judged." },
                  { name: 'Working Man IPA'                   , brewed_by: 'Working Man Brewing Company'           , origin: 'Livermore, California USA', style: 'IPA'   , abv: 6.6, description: "This medium amber beer is infused with a blend of 2-row malted barley and caramel malts. Its balance acquired by using a combination of Pacific Northwest hops for bitterness and aroma." },
                  { name: 'Wyders Dry Apple Cider'            , brewed_by: 'Wyders Cider Company'                  , origin: 'Middlebury, VT, USA', style: 'Cider'   , abv: 4.5, description: "Presenting a soft golden hue, this is a traditional hard cider that is full in body with a smooth apple finish." },
                  { name: 'Stone IPA'                         , brewed_by: 'Stone Brewing Co.'                     , origin: 'Escondido, CA, USA', style: 'IPA'   , abv: 6.9, description: "Originally developed in the late 1700's, British breweries would send beer via sail to the troops and British expatriots in India. Problem was, there was no refrigeration and the ocean voyage took nearly five months. As a result, the beer would usually arrive in compromised condition. Well, the brewers of the time didn't know as much about beer as we do today, but they did know that both hops (where we get the bitterness in beer) and alcohol act as natural preservatives. So, they came up with a brew that was intensely hopped and rather high in alcohol." }
                ])

    Beer.all.each do |b|
        OrgBeerSelection.create(org: org, beer: b)
    end




